// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee.sql

package sqlc

import (
	"context"
)

const countPersonnel = `-- name: CountPersonnel :one
select count(*)::bigint as total
from employees e
join
    employee_details ed
    on ed.employee_id = e.id
    and ed.is_employee_details_new is true
    and ed.language_code = $1
where
    exists (select 1 from employee_socials es where es.employee_id = e.id)
    and e.highest_academic_degree is not null
    and e.speciality is not null
    and e.current_workplace is not null
    and (nullif($2::text, '') is null or e.unique_id = $2)
    and (
        nullif($3::text, '') is null
        or ed.name ilike '%' || $3 || '%'
    )
    and (
        nullif($4::text, '') is null
        or ed.surname ilike '%' || $4 || '%'
    )
    and (
        nullif($5::text, '') is null
        or ed.middlename ilike '%' || $5 || '%'
    )
    and (
        nullif($6::text, '') is null
        or e.current_workplace = $6
    )
`

type CountPersonnelParams struct {
	LanguageCode string `json:"language_code"`
	Uid          string `json:"uid"`
	Name         string `json:"name"`
	Surname      string `json:"surname"`
	Middlename   string `json:"middlename"`
	Workplace    string `json:"workplace"`
}

func (q *Queries) CountPersonnel(ctx context.Context, arg CountPersonnelParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPersonnel,
		arg.LanguageCode,
		arg.Uid,
		arg.Name,
		arg.Surname,
		arg.Middlename,
		arg.Workplace,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createEmployee = `-- name: CreateEmployee :many
INSERT INTO employees (
  unique_id,
  user_id,
  gender,
  tin
) VALUES (
  $1, $2, $3, $4
)
ON CONFLICT (unique_id) DO NOTHING
RETURNING id, unique_id, created_at, updated_at, user_id, gender, tin, highest_academic_degree, speciality, current_workplace
`

type CreateEmployeeParams struct {
	UniqueID string  `json:"unique_id"`
	UserID   *int64  `json:"user_id"`
	Gender   *string `json:"gender"`
	Tin      *string `json:"tin"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, createEmployee,
		arg.UniqueID,
		arg.UserID,
		arg.Gender,
		arg.Tin,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.UniqueID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Gender,
			&i.Tin,
			&i.HighestAcademicDegree,
			&i.Speciality,
			&i.CurrentWorkplace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEmployee = `-- name: DeleteEmployee :exec
delete from employees
where id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
select id, unique_id, created_at, updated_at, user_id, gender, tin, highest_academic_degree, speciality, current_workplace
from employees
where id = $1
`

func (q *Queries) GetEmployeeByID(ctx context.Context, id int64) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UniqueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Gender,
		&i.Tin,
		&i.HighestAcademicDegree,
		&i.Speciality,
		&i.CurrentWorkplace,
	)
	return i, err
}

const getEmployeeByUniqueIdentifier = `-- name: GetEmployeeByUniqueIdentifier :one
select id, unique_id, created_at, updated_at, user_id, gender, tin, highest_academic_degree, speciality, current_workplace
from employees
where unique_id = $1
`

func (q *Queries) GetEmployeeByUniqueIdentifier(ctx context.Context, uniqueID string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUniqueIdentifier, uniqueID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UniqueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Gender,
		&i.Tin,
		&i.HighestAcademicDegree,
		&i.Speciality,
		&i.CurrentWorkplace,
	)
	return i, err
}

const getEmployeeByUserID = `-- name: GetEmployeeByUserID :one
select id, unique_id, created_at, updated_at, user_id, gender, tin, highest_academic_degree, speciality, current_workplace
from employees
where user_id = $1
`

func (q *Queries) GetEmployeeByUserID(ctx context.Context, userID *int64) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUserID, userID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UniqueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Gender,
		&i.Tin,
		&i.HighestAcademicDegree,
		&i.Speciality,
		&i.CurrentWorkplace,
	)
	return i, err
}

const getPersonnelPaginated = `-- name: GetPersonnelPaginated :many
select
    e.id,
    e.unique_id,
    e.gender,
    e.tin,
    e.highest_academic_degree,
    e.speciality,
    e.current_workplace,
    ed.surname,
    ed.name,
    ed.middlename
from employees e
join
    employee_details ed
    on ed.employee_id = e.id
    and ed.is_employee_details_new is true
    and ed.language_code = $1
where
    -- must exist in employee_socials
    exists (select 1 from employee_socials es where es.employee_id = e.id)
    -- required non-null denormalized fields
    and e.highest_academic_degree is not null
    and e.speciality is not null
    and e.current_workplace is not null

    -- optional filters (pass NULL to ignore)
    and (nullif($2::text, '') is null or e.unique_id = $2)
    and (
        nullif($3::text, '') is null
        or ed.name ilike '%' || $3 || '%'
    )
    and (
        nullif($4::text, '') is null
        or ed.surname ilike '%' || $4 || '%'
    )
    and (
        nullif($5::text, '') is null
        or ed.middlename ilike '%' || $5 || '%'
    )
    and (
        nullif($6::text, '') is null
        or e.current_workplace = $6
    )
order by e.id
limit $8
offset $7
`

type GetPersonnelPaginatedParams struct {
	LanguageCode string `json:"language_code"`
	Uid          string `json:"uid"`
	Name         string `json:"name"`
	Surname      string `json:"surname"`
	Middlename   string `json:"middlename"`
	Workplace    string `json:"workplace"`
	Page         int32  `json:"page"`
	Limit        int32  `json:"limit"`
}

type GetPersonnelPaginatedRow struct {
	ID                    int64   `json:"id"`
	UniqueID              string  `json:"unique_id"`
	Gender                *string `json:"gender"`
	Tin                   *string `json:"tin"`
	HighestAcademicDegree *string `json:"highest_academic_degree"`
	Speciality            *string `json:"speciality"`
	CurrentWorkplace      *string `json:"current_workplace"`
	Surname               string  `json:"surname"`
	Name                  string  `json:"name"`
	Middlename            *string `json:"middlename"`
}

func (q *Queries) GetPersonnelPaginated(ctx context.Context, arg GetPersonnelPaginatedParams) ([]GetPersonnelPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getPersonnelPaginated,
		arg.LanguageCode,
		arg.Uid,
		arg.Name,
		arg.Surname,
		arg.Middlename,
		arg.Workplace,
		arg.Page,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPersonnelPaginatedRow{}
	for rows.Next() {
		var i GetPersonnelPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UniqueID,
			&i.Gender,
			&i.Tin,
			&i.HighestAcademicDegree,
			&i.Speciality,
			&i.CurrentWorkplace,
			&i.Surname,
			&i.Name,
			&i.Middlename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueWorkplaces = `-- name: ListUniqueWorkplaces :many
select distinct e.current_workplace
from employees e
join
    employee_details ed
    on ed.employee_id = e.id
    and ed.is_employee_details_new is true
    and ed.language_code = $1
where
    exists (select 1 from employee_socials es where es.employee_id = e.id)
    and e.highest_academic_degree is not null
    and e.speciality is not null
    and e.current_workplace is not null
    and e.current_workplace <> ''
order by e.current_workplace asc
`

func (q *Queries) ListUniqueWorkplaces(ctx context.Context, languageCode string) ([]*string, error) {
	rows, err := q.db.Query(ctx, listUniqueWorkplaces, languageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var current_workplace *string
		if err := rows.Scan(&current_workplace); err != nil {
			return nil, err
		}
		items = append(items, current_workplace)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
