// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee_degree.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployeeDegree = `-- name: CreateEmployeeDegree :one
INSERT INTO employee_degrees(
  employee_id,
  language_code,
  rf_institution_id,
  degree_level,
  institution_name,
  speciality,
  date_start,
  date_end,
  given_by,
  date_degree_recieved
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, employee_id, language_code, institution_name, degree_level, speciality, date_start, date_end, given_by, date_degree_recieved, created_at, updated_at, rf_institution_id
`

type CreateEmployeeDegreeParams struct {
	EmployeeID         int64       `json:"employee_id"`
	LanguageCode       string      `json:"language_code"`
	RfInstitutionID    int64       `json:"rf_institution_id"`
	DegreeLevel        string      `json:"degree_level"`
	InstitutionName    string      `json:"institution_name"`
	Speciality         string      `json:"speciality"`
	DateStart          pgtype.Date `json:"date_start"`
	DateEnd            pgtype.Date `json:"date_end"`
	GivenBy            *string     `json:"given_by"`
	DateDegreeRecieved pgtype.Date `json:"date_degree_recieved"`
}

func (q *Queries) CreateEmployeeDegree(ctx context.Context, arg CreateEmployeeDegreeParams) (EmployeeDegree, error) {
	row := q.db.QueryRow(ctx, createEmployeeDegree,
		arg.EmployeeID,
		arg.LanguageCode,
		arg.RfInstitutionID,
		arg.DegreeLevel,
		arg.InstitutionName,
		arg.Speciality,
		arg.DateStart,
		arg.DateEnd,
		arg.GivenBy,
		arg.DateDegreeRecieved,
	)
	var i EmployeeDegree
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LanguageCode,
		&i.InstitutionName,
		&i.DegreeLevel,
		&i.Speciality,
		&i.DateStart,
		&i.DateEnd,
		&i.GivenBy,
		&i.DateDegreeRecieved,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RfInstitutionID,
	)
	return i, err
}

const deleteEmployeeDegree = `-- name: DeleteEmployeeDegree :exec
DELETE FROM employee_degrees
WHERE id = $1
`

func (q *Queries) DeleteEmployeeDegree(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEmployeeDegree, id)
	return err
}

const getEmployeeDegreeByID = `-- name: GetEmployeeDegreeByID :one
SELECT id, employee_id, language_code, institution_name, degree_level, speciality, date_start, date_end, given_by, date_degree_recieved, created_at, updated_at, rf_institution_id
FROM employee_degrees
WHERE id = $1
`

func (q *Queries) GetEmployeeDegreeByID(ctx context.Context, id int64) (EmployeeDegree, error) {
	row := q.db.QueryRow(ctx, getEmployeeDegreeByID, id)
	var i EmployeeDegree
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LanguageCode,
		&i.InstitutionName,
		&i.DegreeLevel,
		&i.Speciality,
		&i.DateStart,
		&i.DateEnd,
		&i.GivenBy,
		&i.DateDegreeRecieved,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RfInstitutionID,
	)
	return i, err
}

const getEmployeeDegreesByEmployeeIDAndLanguageCode = `-- name: GetEmployeeDegreesByEmployeeIDAndLanguageCode :many
SELECT id, employee_id, language_code, institution_name, degree_level, speciality, date_start, date_end, given_by, date_degree_recieved, created_at, updated_at, rf_institution_id
FROM employee_degrees
WHERE employee_id = $1 AND language_code = $2
ORDER BY employee_degrees.date_degree_recieved DESC
`

type GetEmployeeDegreesByEmployeeIDAndLanguageCodeParams struct {
	EmployeeID   int64  `json:"employee_id"`
	LanguageCode string `json:"language_code"`
}

func (q *Queries) GetEmployeeDegreesByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeeDegreesByEmployeeIDAndLanguageCodeParams) ([]EmployeeDegree, error) {
	rows, err := q.db.Query(ctx, getEmployeeDegreesByEmployeeIDAndLanguageCode, arg.EmployeeID, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmployeeDegree{}
	for rows.Next() {
		var i EmployeeDegree
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.LanguageCode,
			&i.InstitutionName,
			&i.DegreeLevel,
			&i.Speciality,
			&i.DateStart,
			&i.DateEnd,
			&i.GivenBy,
			&i.DateDegreeRecieved,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RfInstitutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeeDegree = `-- name: UpdateEmployeeDegree :one
UPDATE employee_degrees
SET
  rf_institution_id    = COALESCE($1, rf_institution_id),
  degree_level          = COALESCE($2, degree_level),
  institution_name      = COALESCE($3, institution_name),
  speciality            = COALESCE($4, speciality),
  date_start            = COALESCE($5, date_start),
  date_end              = COALESCE($6, date_end),
  given_by              = COALESCE($7, given_by),
  date_degree_recieved  = COALESCE($8, date_degree_recieved),
  updated_at = now()
WHERE id = $9
RETURNING id, employee_id, language_code, institution_name, degree_level, speciality, date_start, date_end, given_by, date_degree_recieved, created_at, updated_at, rf_institution_id
`

type UpdateEmployeeDegreeParams struct {
	RfInstitutionID    *int64      `json:"rf_institution_id"`
	DegreeLevel        *string     `json:"degree_level"`
	InstitutionName    *string     `json:"institution_name"`
	Speciality         *string     `json:"speciality"`
	DateStart          pgtype.Date `json:"date_start"`
	DateEnd            pgtype.Date `json:"date_end"`
	GivenBy            *string     `json:"given_by"`
	DateDegreeRecieved pgtype.Date `json:"date_degree_recieved"`
	ID                 int64       `json:"id"`
}

func (q *Queries) UpdateEmployeeDegree(ctx context.Context, arg UpdateEmployeeDegreeParams) (EmployeeDegree, error) {
	row := q.db.QueryRow(ctx, updateEmployeeDegree,
		arg.RfInstitutionID,
		arg.DegreeLevel,
		arg.InstitutionName,
		arg.Speciality,
		arg.DateStart,
		arg.DateEnd,
		arg.GivenBy,
		arg.DateDegreeRecieved,
		arg.ID,
	)
	var i EmployeeDegree
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LanguageCode,
		&i.InstitutionName,
		&i.DegreeLevel,
		&i.Speciality,
		&i.DateStart,
		&i.DateEnd,
		&i.GivenBy,
		&i.DateDegreeRecieved,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RfInstitutionID,
	)
	return i, err
}
