// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee_publication.sql

package sqlc

import (
	"context"
)

const createEmployeePublication = `-- name: CreateEmployeePublication :one
INSERT INTO employee_publications(
  employee_id,
  language_code,
  rf_publication_type_id,
  name,
  type,
  authors,
  journal_name,
  volume,
  number,
  pages,
  year,
  link
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, employee_id, language_code, rf_publication_type_id, name, type, authors, journal_name, volume, number, pages, year, link, created_at, updated_at
`

type CreateEmployeePublicationParams struct {
	EmployeeID          int64   `json:"employee_id"`
	LanguageCode        string  `json:"language_code"`
	RfPublicationTypeID int64   `json:"rf_publication_type_id"`
	Name                string  `json:"name"`
	Type                string  `json:"type"`
	Authors             *string `json:"authors"`
	JournalName         *string `json:"journal_name"`
	Volume              *string `json:"volume"`
	Number              *string `json:"number"`
	Pages               *string `json:"pages"`
	Year                *int32  `json:"year"`
	Link                string  `json:"link"`
}

func (q *Queries) CreateEmployeePublication(ctx context.Context, arg CreateEmployeePublicationParams) (EmployeePublication, error) {
	row := q.db.QueryRow(ctx, createEmployeePublication,
		arg.EmployeeID,
		arg.LanguageCode,
		arg.RfPublicationTypeID,
		arg.Name,
		arg.Type,
		arg.Authors,
		arg.JournalName,
		arg.Volume,
		arg.Number,
		arg.Pages,
		arg.Year,
		arg.Link,
	)
	var i EmployeePublication
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LanguageCode,
		&i.RfPublicationTypeID,
		&i.Name,
		&i.Type,
		&i.Authors,
		&i.JournalName,
		&i.Volume,
		&i.Number,
		&i.Pages,
		&i.Year,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmployeePublication = `-- name: DeleteEmployeePublication :exec
DELETE FROM employee_publications
WHERE id = $1
`

func (q *Queries) DeleteEmployeePublication(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEmployeePublication, id)
	return err
}

const getEmployeePublicationByID = `-- name: GetEmployeePublicationByID :one
SELECT id, employee_id, language_code, rf_publication_type_id, name, type, authors, journal_name, volume, number, pages, year, link, created_at, updated_at
FROM employee_publications
WHERE id = $1
`

func (q *Queries) GetEmployeePublicationByID(ctx context.Context, id int64) (EmployeePublication, error) {
	row := q.db.QueryRow(ctx, getEmployeePublicationByID, id)
	var i EmployeePublication
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LanguageCode,
		&i.RfPublicationTypeID,
		&i.Name,
		&i.Type,
		&i.Authors,
		&i.JournalName,
		&i.Volume,
		&i.Number,
		&i.Pages,
		&i.Year,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeePublicationsByEmployeeIDAndLanguageCode = `-- name: GetEmployeePublicationsByEmployeeIDAndLanguageCode :many
SELECT id, employee_id, language_code, rf_publication_type_id, name, type, authors, journal_name, volume, number, pages, year, link, created_at, updated_at
FROM employee_publications
WHERE employee_id = $1 AND language_code = $2
`

type GetEmployeePublicationsByEmployeeIDAndLanguageCodeParams struct {
	EmployeeID   int64  `json:"employee_id"`
	LanguageCode string `json:"language_code"`
}

func (q *Queries) GetEmployeePublicationsByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeePublicationsByEmployeeIDAndLanguageCodeParams) ([]EmployeePublication, error) {
	rows, err := q.db.Query(ctx, getEmployeePublicationsByEmployeeIDAndLanguageCode, arg.EmployeeID, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmployeePublication{}
	for rows.Next() {
		var i EmployeePublication
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.LanguageCode,
			&i.RfPublicationTypeID,
			&i.Name,
			&i.Type,
			&i.Authors,
			&i.JournalName,
			&i.Volume,
			&i.Number,
			&i.Pages,
			&i.Year,
			&i.Link,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeePublication = `-- name: UpdateEmployeePublication :one
UPDATE employee_publications 
SET 
  rf_publication_type_id = COALESCE($1, rf_publication_type_id),
  name = COALESCE($2, name),
  type = COALESCE($3, type),
  authors = COALESCE($4, authors),
  journal_name = COALESCE($5, journal_name),
  volume = COALESCE($6, volume),
  number = COALESCE($7, number),
  pages = COALESCE($8, pages),
  year = COALESCE($9, year),
  link = COALESCE($10, link),
  updated_at = now()
WHERE id = $11
RETURNING id, employee_id, language_code, rf_publication_type_id, name, type, authors, journal_name, volume, number, pages, year, link, created_at, updated_at
`

type UpdateEmployeePublicationParams struct {
	RfPublicationTypeID *int64  `json:"rf_publication_type_id"`
	Name                *string `json:"name"`
	Type                *string `json:"type"`
	Authors             *string `json:"authors"`
	JournalName         *string `json:"journal_name"`
	Volume              *string `json:"volume"`
	Number              *string `json:"number"`
	Pages               *string `json:"pages"`
	Year                *int32  `json:"year"`
	Link                *string `json:"link"`
	ID                  int64   `json:"id"`
}

func (q *Queries) UpdateEmployeePublication(ctx context.Context, arg UpdateEmployeePublicationParams) (EmployeePublication, error) {
	row := q.db.QueryRow(ctx, updateEmployeePublication,
		arg.RfPublicationTypeID,
		arg.Name,
		arg.Type,
		arg.Authors,
		arg.JournalName,
		arg.Volume,
		arg.Number,
		arg.Pages,
		arg.Year,
		arg.Link,
		arg.ID,
	)
	var i EmployeePublication
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LanguageCode,
		&i.RfPublicationTypeID,
		&i.Name,
		&i.Type,
		&i.Authors,
		&i.JournalName,
		&i.Volume,
		&i.Number,
		&i.Pages,
		&i.Year,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
