// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: institution_details.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstitutionDetails = `-- name: CreateInstitutionDetails :one
INSERT INTO institution_details(
  institution_id,
  language_code,
  institution_type,
  institution_title_short,
  institution_title_long,
  legal_status,
  mission,
  founder,
  legal_address,
  factual_address,
  city
  )
VALUES (
 $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, created_at, updated_at
`

type CreateInstitutionDetailsParams struct {
	InstitutionID         int64   `json:"institution_id"`
	LanguageCode          string  `json:"language_code"`
	InstitutionType       string  `json:"institution_type"`
	InstitutionTitleShort string  `json:"institution_title_short"`
	InstitutionTitleLong  string  `json:"institution_title_long"`
	LegalStatus           *string `json:"legal_status"`
	Mission               *string `json:"mission"`
	Founder               *string `json:"founder"`
	LegalAddress          string  `json:"legal_address"`
	FactualAddress        *string `json:"factual_address"`
	City                  *string `json:"city"`
}

type CreateInstitutionDetailsRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateInstitutionDetails(ctx context.Context, arg CreateInstitutionDetailsParams) (CreateInstitutionDetailsRow, error) {
	row := q.db.QueryRow(ctx, createInstitutionDetails,
		arg.InstitutionID,
		arg.LanguageCode,
		arg.InstitutionType,
		arg.InstitutionTitleShort,
		arg.InstitutionTitleLong,
		arg.LegalStatus,
		arg.Mission,
		arg.Founder,
		arg.LegalAddress,
		arg.FactualAddress,
		arg.City,
	)
	var i CreateInstitutionDetailsRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteInstitutionDetails = `-- name: DeleteInstitutionDetails :exec
DELETE FROM institution_details 
WHERE id = $1
`

func (q *Queries) DeleteInstitutionDetails(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInstitutionDetails, id)
	return err
}

const getInstitutionDetailsByID = `-- name: GetInstitutionDetailsByID :one
SELECT id, institution_id, language_code, institution_type, legal_status, mission, founder, legal_address, factual_address, created_at, updated_at, institution_title_short, institution_title_long, city
FROM institution_details
WHERE id = $1
`

func (q *Queries) GetInstitutionDetailsByID(ctx context.Context, id int64) (InstitutionDetail, error) {
	row := q.db.QueryRow(ctx, getInstitutionDetailsByID, id)
	var i InstitutionDetail
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.LanguageCode,
		&i.InstitutionType,
		&i.LegalStatus,
		&i.Mission,
		&i.Founder,
		&i.LegalAddress,
		&i.FactualAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstitutionTitleShort,
		&i.InstitutionTitleLong,
		&i.City,
	)
	return i, err
}

const getInstitutionDetailsByInstitutionIDAndLanguage = `-- name: GetInstitutionDetailsByInstitutionIDAndLanguage :one
SELECT id, institution_id, language_code, institution_type, legal_status, mission, founder, legal_address, factual_address, created_at, updated_at, institution_title_short, institution_title_long, city
FROM institution_details
WHERE institution_id = $1 AND language_code = $2
`

type GetInstitutionDetailsByInstitutionIDAndLanguageParams struct {
	InstitutionID int64  `json:"institution_id"`
	LanguageCode  string `json:"language_code"`
}

func (q *Queries) GetInstitutionDetailsByInstitutionIDAndLanguage(ctx context.Context, arg GetInstitutionDetailsByInstitutionIDAndLanguageParams) (InstitutionDetail, error) {
	row := q.db.QueryRow(ctx, getInstitutionDetailsByInstitutionIDAndLanguage, arg.InstitutionID, arg.LanguageCode)
	var i InstitutionDetail
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.LanguageCode,
		&i.InstitutionType,
		&i.LegalStatus,
		&i.Mission,
		&i.Founder,
		&i.LegalAddress,
		&i.FactualAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstitutionTitleShort,
		&i.InstitutionTitleLong,
		&i.City,
	)
	return i, err
}

const getInstitutionNamesByLanguageCode = `-- name: GetInstitutionNamesByLanguageCode :many
SELECT institution_title_long
FROM institution_details
WHERE language_code = $1
`

func (q *Queries) GetInstitutionNamesByLanguageCode(ctx context.Context, languageCode string) ([]string, error) {
	rows, err := q.db.Query(ctx, getInstitutionNamesByLanguageCode, languageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var institution_title_long string
		if err := rows.Scan(&institution_title_long); err != nil {
			return nil, err
		}
		items = append(items, institution_title_long)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInsitutionDetails = `-- name: UpdateInsitutionDetails :one
UPDATE institution_details
SET 
  institution_type = COALESCE($1, institution_type),
  institution_title_long = COALESCE($2, institution_title_long),
  institution_title_short = COALESCE($3, institution_title_short),
  legal_status = COALESCE($4, legal_status),
  mission = COALESCE($5, mission),
  founder = COALESCE($6, founder),
  legal_address = COALESCE($7, legal_address),
  factual_address = COALESCE($8, factual_address),
  city = COALESCE($9, city),
  updated_at = now()
WHERE id = $10
RETURNING id, created_at, updated_at
`

type UpdateInsitutionDetailsParams struct {
	InstitutionType       string  `json:"institution_type"`
	InstitutionTitleLong  string  `json:"institution_title_long"`
	InstitutionTitleShort string  `json:"institution_title_short"`
	LegalStatus           *string `json:"legal_status"`
	Mission               *string `json:"mission"`
	Founder               *string `json:"founder"`
	LegalAddress          string  `json:"legal_address"`
	FactualAddress        *string `json:"factual_address"`
	City                  *string `json:"city"`
	ID                    int64   `json:"id"`
}

type UpdateInsitutionDetailsRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateInsitutionDetails(ctx context.Context, arg UpdateInsitutionDetailsParams) (UpdateInsitutionDetailsRow, error) {
	row := q.db.QueryRow(ctx, updateInsitutionDetails,
		arg.InstitutionType,
		arg.InstitutionTitleLong,
		arg.InstitutionTitleShort,
		arg.LegalStatus,
		arg.Mission,
		arg.Founder,
		arg.LegalAddress,
		arg.FactualAddress,
		arg.City,
		arg.ID,
	)
	var i UpdateInsitutionDetailsRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
