// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID                    int64              `json:"id"`
	UniqueID              string             `json:"unique_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	UserID                *int64             `json:"user_id"`
	Gender                *string            `json:"gender"`
	Tin                   *string            `json:"tin"`
	HighestAcademicDegree *string            `json:"highest_academic_degree"`
	Speciality            *string            `json:"speciality"`
	CurrentWorkplace      *string            `json:"current_workplace"`
}

type EmployeeDegree struct {
	ID                 int64              `json:"id"`
	EmployeeID         int64              `json:"employee_id"`
	LanguageCode       string             `json:"language_code"`
	InstitutionName    string             `json:"institution_name"`
	DegreeLevel        string             `json:"degree_level"`
	Speciality         string             `json:"speciality"`
	DateStart          pgtype.Date        `json:"date_start"`
	DateEnd            pgtype.Date        `json:"date_end"`
	GivenBy            *string            `json:"given_by"`
	DateDegreeRecieved pgtype.Date        `json:"date_degree_recieved"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RfInstitutionID    int64              `json:"rf_institution_id"`
}

type EmployeeDetail struct {
	ID                   int64              `json:"id"`
	EmployeeID           int64              `json:"employee_id"`
	LanguageCode         string             `json:"language_code"`
	Surname              string             `json:"surname"`
	Name                 string             `json:"name"`
	Middlename           *string            `json:"middlename"`
	IsEmployeeDetailsNew bool               `json:"is_employee_details_new"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeMainResearchArea struct {
	ID           int64              `json:"id"`
	EmployeeID   int64              `json:"employee_id"`
	LanguageCode string             `json:"language_code"`
	Area         string             `json:"area"`
	Discipline   string             `json:"discipline"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeMainResearchAreaKeyTopic struct {
	ID                         int64              `json:"id"`
	EmployeeMainResearchAreaID int64              `json:"employee_main_research_area_id"`
	KeyTopicTitle              string             `json:"key_topic_title"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeParticipationInEvent struct {
	ID           int64              `json:"id"`
	EmployeeID   int64              `json:"employee_id"`
	LanguageCode string             `json:"language_code"`
	EventTitle   string             `json:"event_title"`
	EventDate    pgtype.Date        `json:"event_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeParticipationInProfessionalCommunity struct {
	ID                          int64              `json:"id"`
	EmployeeID                  int64              `json:"employee_id"`
	ProfessionalCommunityTitle  string             `json:"professional_community_title"`
	LanguageCode                string             `json:"language_code"`
	RoleInProfessionalCommunity string             `json:"role_in_professional_community"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

type EmployeePatent struct {
	ID           int64              `json:"id"`
	EmployeeID   int64              `json:"employee_id"`
	LanguageCode string             `json:"language_code"`
	PatentTitle  string             `json:"patent_title"`
	Description  string             `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EmployeePublication struct {
	ID                  int64              `json:"id"`
	EmployeeID          int64              `json:"employee_id"`
	LanguageCode        string             `json:"language_code"`
	RfPublicationTypeID int64              `json:"rf_publication_type_id"`
	Name                string             `json:"name"`
	Type                string             `json:"type"`
	Authors             *string            `json:"authors"`
	JournalName         *string            `json:"journal_name"`
	Volume              *string            `json:"volume"`
	Number              *string            `json:"number"`
	Pages               *string            `json:"pages"`
	Year                *int32             `json:"year"`
	Link                string             `json:"link"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeRefresherCourse struct {
	ID           int64              `json:"id"`
	EmployeeID   int64              `json:"employee_id"`
	LanguageCode string             `json:"language_code"`
	CourseTitle  string             `json:"course_title"`
	DateStart    pgtype.Date        `json:"date_start"`
	DateEnd      pgtype.Date        `json:"date_end"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeResearchActivity struct {
	ID                    int64              `json:"id"`
	EmployeeID            int64              `json:"employee_id"`
	LanguageCode          string             `json:"language_code"`
	ResearchActivityTitle string             `json:"research_activity_title"`
	EmployeeRole          string             `json:"employee_role"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeScientificAward struct {
	ID                   int64              `json:"id"`
	EmployeeID           int64              `json:"employee_id"`
	LanguageCode         string             `json:"language_code"`
	ScientificAwardTitle string             `json:"scientific_award_title"`
	GivenBy              string             `json:"given_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeSocial struct {
	ID           int64              `json:"id"`
	EmployeeID   int64              `json:"employee_id"`
	SocialName   string             `json:"social_name"`
	LinkToSocial string             `json:"link_to_social"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeWorkExperience struct {
	ID           int64              `json:"id"`
	EmployeeID   int64              `json:"employee_id"`
	LanguageCode string             `json:"language_code"`
	Workplace    string             `json:"workplace"`
	JobTitle     string             `json:"job_title"`
	Description  string             `json:"description"`
	DateStart    pgtype.Date        `json:"date_start"`
	DateEnd      pgtype.Date        `json:"date_end"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	OnGoing      bool               `json:"on_going"`
}

type Institution struct {
	ID                  int64              `json:"id"`
	YearOfEstablishment *int32             `json:"year_of_establishment"`
	Email               string             `json:"email"`
	Fax                 *string            `json:"fax"`
	OfficialWebsite     string             `json:"official_website"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	PhoneNumber         *string            `json:"phone_number"`
	MailIndex           *string            `json:"mail_index"`
}

type InstitutionAccreditation struct {
	ID                int64              `json:"id"`
	InstitutionID     int64              `json:"institution_id"`
	LanguageCode      string             `json:"language_code"`
	AccreditationType string             `json:"accreditation_type"`
	GivenBy           string             `json:"given_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionAchievement struct {
	ID               int64              `json:"id"`
	InstitutionID    int64              `json:"institution_id"`
	LanguageCode     string             `json:"language_code"`
	AchievementTitle string             `json:"achievement_title"`
	AchievementType  string             `json:"achievement_type"`
	DateRecieved     pgtype.Date        `json:"date_recieved"`
	GivenBy          string             `json:"given_by"`
	LinkToFile       string             `json:"link_to_file"`
	Description      *string            `json:"description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionConference struct {
	ID               int64              `json:"id"`
	InstitutionID    int64              `json:"institution_id"`
	LanguageCode     string             `json:"language_code"`
	ConferenceTitle  string             `json:"conference_title"`
	Link             string             `json:"link"`
	LinkToRinc       *string            `json:"link_to_rinc"`
	DateOfConference pgtype.Date        `json:"date_of_conference"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionDetail struct {
	ID                    int64              `json:"id"`
	InstitutionID         int64              `json:"institution_id"`
	LanguageCode          string             `json:"language_code"`
	InstitutionType       string             `json:"institution_type"`
	LegalStatus           *string            `json:"legal_status"`
	Mission               *string            `json:"mission"`
	Founder               *string            `json:"founder"`
	LegalAddress          string             `json:"legal_address"`
	FactualAddress        *string            `json:"factual_address"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	InstitutionTitleShort string             `json:"institution_title_short"`
	InstitutionTitleLong  string             `json:"institution_title_long"`
	City                  *string            `json:"city"`
}

type InstitutionLicence struct {
	ID            int64              `json:"id"`
	InstitutionID int64              `json:"institution_id"`
	LanguageCode  string             `json:"language_code"`
	LicenceTitle  string             `json:"licence_title"`
	LicenceType   string             `json:"licence_type"`
	LinkToFile    string             `json:"link_to_file"`
	GivenBy       string             `json:"given_by"`
	DateStart     pgtype.Date        `json:"date_start"`
	DateEnd       pgtype.Date        `json:"date_end"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionMagazine struct {
	ID            int64              `json:"id"`
	InstitutionID int64              `json:"institution_id"`
	LanguageCode  string             `json:"language_code"`
	MagazineName  string             `json:"magazine_name"`
	Link          string             `json:"link"`
	LinkToRinc    *string            `json:"link_to_rinc"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionMainResearchDirection struct {
	ID                     int64              `json:"id"`
	InstitutionID          int64              `json:"institution_id"`
	LanguageCode           string             `json:"language_code"`
	ResearchDirectionTitle string             `json:"research_direction_title"`
	Discipline             string             `json:"discipline"`
	AreaOfResearch         *string            `json:"area_of_research"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionPartnership struct {
	ID             int64              `json:"id"`
	InstitutionID  int64              `json:"institution_id"`
	LanguageCode   string             `json:"language_code"`
	PartnerName    string             `json:"partner_name"`
	PartnerType    string             `json:"partner_type"`
	DateOfContract pgtype.Date        `json:"date_of_contract"`
	LinkToPartner  string             `json:"link_to_partner"`
	Goal           string             `json:"goal"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionPatent struct {
	ID               int64              `json:"id"`
	InstitutionID    int64              `json:"institution_id"`
	LanguageCode     string             `json:"language_code"`
	PatentTitle      string             `json:"patent_title"`
	Discipline       string             `json:"discipline"`
	Description      string             `json:"description"`
	ImplementedIn    string             `json:"implemented_in"`
	LinkToPatentFile string             `json:"link_to_patent_file"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionProject struct {
	ID              int64              `json:"id"`
	InstitutionID   int64              `json:"institution_id"`
	LanguageCode    string             `json:"language_code"`
	ProjectType     string             `json:"project_type"`
	ProjectTitle    string             `json:"project_title"`
	DateStart       pgtype.Date        `json:"date_start"`
	DateEnd         pgtype.Date        `json:"date_end"`
	Fund            float64            `json:"fund"`
	InstitutionRole string             `json:"institution_role"`
	Coordinator     string             `json:"coordinator"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionProjectPartner struct {
	ID                   int64              `json:"id"`
	InstitutionProjectID int64              `json:"institution_project_id"`
	LanguageCode         string             `json:"language_code"`
	PartnerType          string             `json:"partner_type"`
	PartnerName          string             `json:"partner_name"`
	LinkToPartner        string             `json:"link_to_partner"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionRanking struct {
	ID                  int64              `json:"id"`
	InstitutionID       int64              `json:"institution_id"`
	LanguageCode        string             `json:"language_code"`
	RankingTitle        string             `json:"ranking_title"`
	RankingType         string             `json:"ranking_type"`
	DateRecieved        pgtype.Date        `json:"date_recieved"`
	RankingAgency       string             `json:"ranking_agency"`
	LinkToRankingFile   string             `json:"link_to_ranking_file"`
	Description         *string            `json:"description"`
	LinkToRankingAgency string             `json:"link_to_ranking_agency"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionResearchSupportInfrastructure struct {
	ID                                 int64              `json:"id"`
	InstitutionID                      int64              `json:"institution_id"`
	LanguageCode                       string             `json:"language_code"`
	ResearchSupportInfrastructureTitle string             `json:"research_support_infrastructure_title"`
	ResearchSupportInfrastructureType  string             `json:"research_support_infrastructure_type"`
	TinOfLegalEntity                   string             `json:"tin_of_legal_entity"`
	CreatedAt                          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                          pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionSocial struct {
	ID            int64              `json:"id"`
	InstitutionID int64              `json:"institution_id"`
	LinkToSocial  string             `json:"link_to_social"`
	SocialName    string             `json:"social_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RfInstitution struct {
	ID          int64              `json:"id"`
	PostalCode  *string            `json:"postal_code"`
	Email       *string            `json:"email"`
	Website     *string            `json:"website"`
	PhoneNumber *string            `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RfInstitutionName struct {
	ID              int64              `json:"id"`
	RfInstitutionID int64              `json:"rf_institution_id"`
	LanguageCode    string             `json:"language_code"`
	Name            string             `json:"name"`
	NameNorm        string             `json:"name_norm"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RfPublicationType struct {
	ID           int64              `json:"id"`
	LanguageCode string             `json:"language_code"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserSession struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
