// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountPersonnel(ctx context.Context, arg CountPersonnelParams) (int64, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) ([]Employee, error)
	CreateEmployeeDegree(ctx context.Context, arg CreateEmployeeDegreeParams) (EmployeeDegree, error)
	CreateEmployeeDetails(ctx context.Context, arg CreateEmployeeDetailsParams) (CreateEmployeeDetailsRow, error)
	CreateEmployeeMainResearchArea(ctx context.Context, arg CreateEmployeeMainResearchAreaParams) (EmployeeMainResearchArea, error)
	CreateEmployeeMainResearchAreaKeyTopic(ctx context.Context, arg CreateEmployeeMainResearchAreaKeyTopicParams) (EmployeeMainResearchAreaKeyTopic, error)
	CreateEmployeeParticipationInEvent(ctx context.Context, arg CreateEmployeeParticipationInEventParams) (EmployeeParticipationInEvent, error)
	CreateEmployeeParticipationInProfessionalCommunity(ctx context.Context, arg CreateEmployeeParticipationInProfessionalCommunityParams) (EmployeeParticipationInProfessionalCommunity, error)
	CreateEmployeePatent(ctx context.Context, arg CreateEmployeePatentParams) (EmployeePatent, error)
	CreateEmployeePublication(ctx context.Context, arg CreateEmployeePublicationParams) (EmployeePublication, error)
	CreateEmployeeRefresherCourse(ctx context.Context, arg CreateEmployeeRefresherCourseParams) (EmployeeRefresherCourse, error)
	CreateEmployeeResearchActivity(ctx context.Context, arg CreateEmployeeResearchActivityParams) (EmployeeResearchActivity, error)
	CreateEmployeeScientificAward(ctx context.Context, arg CreateEmployeeScientificAwardParams) (EmployeeScientificAward, error)
	CreateEmployeeSocial(ctx context.Context, arg CreateEmployeeSocialParams) (EmployeeSocial, error)
	CreateEmployeeWorkExperience(ctx context.Context, arg CreateEmployeeWorkExperienceParams) (EmployeeWorkExperience, error)
	CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (CreateInstitutionRow, error)
	CreateInstitutionAccreditation(ctx context.Context, arg CreateInstitutionAccreditationParams) (CreateInstitutionAccreditationRow, error)
	CreateInstitutionAchievement(ctx context.Context, arg CreateInstitutionAchievementParams) (CreateInstitutionAchievementRow, error)
	CreateInstitutionConference(ctx context.Context, arg CreateInstitutionConferenceParams) (CreateInstitutionConferenceRow, error)
	CreateInstitutionDetails(ctx context.Context, arg CreateInstitutionDetailsParams) (CreateInstitutionDetailsRow, error)
	CreateInstitutionLicence(ctx context.Context, arg CreateInstitutionLicenceParams) (CreateInstitutionLicenceRow, error)
	CreateInstitutionMagazine(ctx context.Context, arg CreateInstitutionMagazineParams) (CreateInstitutionMagazineRow, error)
	CreateInstitutionMainResearchDirection(ctx context.Context, arg CreateInstitutionMainResearchDirectionParams) (CreateInstitutionMainResearchDirectionRow, error)
	CreateInstitutionPartnership(ctx context.Context, arg CreateInstitutionPartnershipParams) (CreateInstitutionPartnershipRow, error)
	CreateInstitutionPatent(ctx context.Context, arg CreateInstitutionPatentParams) (CreateInstitutionPatentRow, error)
	CreateInstitutionProject(ctx context.Context, arg CreateInstitutionProjectParams) (CreateInstitutionProjectRow, error)
	CreateInstitutionProjectPartner(ctx context.Context, arg CreateInstitutionProjectPartnerParams) (CreateInstitutionProjectPartnerRow, error)
	CreateInstitutionRanking(ctx context.Context, arg CreateInstitutionRankingParams) (CreateInstitutionRankingRow, error)
	CreateInstitutionResearchSupportInfrastructure(ctx context.Context, arg CreateInstitutionResearchSupportInfrastructureParams) (CreateInstitutionResearchSupportInfrastructureRow, error)
	CreateInstitutionSocial(ctx context.Context, arg CreateInstitutionSocialParams) (CreateInstitutionSocialRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (CreateUserSessionRow, error)
	DeleteEmployee(ctx context.Context, id int64) error
	DeleteEmployeeDegree(ctx context.Context, id int64) error
	DeleteEmployeeDetails(ctx context.Context, id int64) error
	DeleteEmployeeMainResearchArea(ctx context.Context, id int64) error
	DeleteEmployeeMainResearchAreaKeyTopic(ctx context.Context, id int64) error
	DeleteEmployeeMainResearchAreaKeyTopicsByEmployeeMainResearchAreaID(ctx context.Context, employeeMainResearchAreaID int64) error
	DeleteEmployeeParticipationInEvent(ctx context.Context, id int64) error
	DeleteEmployeeParticipationInProfessionalCommunity(ctx context.Context, id int64) error
	DeleteEmployeePatent(ctx context.Context, id int64) error
	DeleteEmployeePublication(ctx context.Context, id int64) error
	DeleteEmployeeRefresherCourse(ctx context.Context, id int64) error
	DeleteEmployeeResearchActivity(ctx context.Context, id int64) error
	DeleteEmployeeScientificAward(ctx context.Context, id int64) error
	DeleteEmployeeSocial(ctx context.Context, id int64) error
	DeleteEmployeeWorkExperience(ctx context.Context, id int64) error
	DeleteInsitution(ctx context.Context, id int64) error
	DeleteInstitutionAccreditation(ctx context.Context, id int64) error
	DeleteInstitutionAchivement(ctx context.Context, id int64) error
	DeleteInstitutionConference(ctx context.Context, id int64) error
	DeleteInstitutionDetails(ctx context.Context, id int64) error
	DeleteInstitutionLicence(ctx context.Context, id int64) error
	DeleteInstitutionMagazine(ctx context.Context, id int64) error
	DeleteInstitutionMainResearchDirection(ctx context.Context, id int64) error
	DeleteInstitutionPartnership(ctx context.Context, id int64) error
	DeleteInstitutionPatent(ctx context.Context, id int64) error
	DeleteInstitutionProject(ctx context.Context, id int64) error
	DeleteInstitutionProjectPartner(ctx context.Context, id int64) error
	DeleteInstitutionRanking(ctx context.Context, id int64) error
	DeleteInstitutionResearchSupportInfrastructure(ctx context.Context, id int64) error
	DeleteInstitutionSocial(ctx context.Context, id int64) error
	DeleteUserSessionByID(ctx context.Context, id int64) error
	DeleteUserSessionByUserID(ctx context.Context, userID int64) error
	GetAllInstitutions(ctx context.Context) ([]Institution, error)
	GetCurrentEmployeeDetailsByEmployeeIDAndLanguageCode(ctx context.Context, arg GetCurrentEmployeeDetailsByEmployeeIDAndLanguageCodeParams) (EmployeeDetail, error)
	GetEmployeeByID(ctx context.Context, id int64) (Employee, error)
	GetEmployeeByUniqueIdentifier(ctx context.Context, uniqueID string) (Employee, error)
	GetEmployeeByUserID(ctx context.Context, userID *int64) (Employee, error)
	GetEmployeeDegreeByID(ctx context.Context, id int64) (EmployeeDegree, error)
	GetEmployeeDegreesByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeeDegreesByEmployeeIDAndLanguageCodeParams) ([]EmployeeDegree, error)
	GetEmployeeDetailsByEmployeeID(ctx context.Context, employeeID int64) ([]EmployeeDetail, error)
	GetEmployeeDetailsByID(ctx context.Context, id int64) (EmployeeDetail, error)
	GetEmployeeMainResearchAreaByID(ctx context.Context, id int64) (EmployeeMainResearchArea, error)
	GetEmployeeMainResearchAreaKeyTopicByID(ctx context.Context, id int64) (EmployeeMainResearchAreaKeyTopic, error)
	GetEmployeeMainResearchAreaKeyTopicsByEmployeeMainResearchAreaIDAndLanguageCode(ctx context.Context, employeeMainResearchAreaID int64) ([]EmployeeMainResearchAreaKeyTopic, error)
	GetEmployeeMainResearchAreasByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeeMainResearchAreasByEmployeeIDAndLanguageCodeParams) ([]EmployeeMainResearchArea, error)
	GetEmployeeParticipationInEventByID(ctx context.Context, id int64) (EmployeeParticipationInEvent, error)
	GetEmployeeParticipationInEventsByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeeParticipationInEventsByEmployeeIDAndLanguageCodeParams) ([]EmployeeParticipationInEvent, error)
	GetEmployeeParticipationInProfessionalCommunityByID(ctx context.Context, id int64) (EmployeeParticipationInProfessionalCommunity, error)
	GetEmployeeParticipationInProfessionalCommunitysByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeeParticipationInProfessionalCommunitysByEmployeeIDAndLanguageCodeParams) ([]EmployeeParticipationInProfessionalCommunity, error)
	GetEmployeePatentByID(ctx context.Context, id int64) (EmployeePatent, error)
	GetEmployeePatentsByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeePatentsByEmployeeIDAndLanguageCodeParams) ([]EmployeePatent, error)
	GetEmployeePublicationByID(ctx context.Context, id int64) (EmployeePublication, error)
	GetEmployeePublicationsByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeePublicationsByEmployeeIDAndLanguageCodeParams) ([]EmployeePublication, error)
	GetEmployeeRefresherCourseByID(ctx context.Context, id int64) (EmployeeRefresherCourse, error)
	GetEmployeeRefresherCoursesByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeeRefresherCoursesByEmployeeIDAndLanguageCodeParams) ([]EmployeeRefresherCourse, error)
	GetEmployeeResearchActivitiesByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeeResearchActivitiesByEmployeeIDAndLanguageCodeParams) ([]EmployeeResearchActivity, error)
	GetEmployeeResearchActivityByID(ctx context.Context, id int64) (EmployeeResearchActivity, error)
	GetEmployeeScientificAwardByID(ctx context.Context, id int64) (EmployeeScientificAward, error)
	GetEmployeeScientificAwardsByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeeScientificAwardsByEmployeeIDAndLanguageCodeParams) ([]EmployeeScientificAward, error)
	GetEmployeeSocialByID(ctx context.Context, id int64) (EmployeeSocial, error)
	GetEmployeeSocialsByEmployeeID(ctx context.Context, employeeID int64) ([]EmployeeSocial, error)
	GetEmployeeWorkExperienceByID(ctx context.Context, id int64) (EmployeeWorkExperience, error)
	GetEmployeeWorkExperiencesByEmployeeIDAndLanguageCode(ctx context.Context, arg GetEmployeeWorkExperiencesByEmployeeIDAndLanguageCodeParams) ([]EmployeeWorkExperience, error)
	GetInstitutionAccreditationByID(ctx context.Context, id int64) (InstitutionAccreditation, error)
	GetInstitutionAccreditationsByInstitutionIDAndLanguageCode(ctx context.Context, arg GetInstitutionAccreditationsByInstitutionIDAndLanguageCodeParams) ([]InstitutionAccreditation, error)
	GetInstitutionAchievementByID(ctx context.Context, id int64) (InstitutionAchievement, error)
	GetInstitutionAchievementsByInstitutionIDAndLanguageCode(ctx context.Context, arg GetInstitutionAchievementsByInstitutionIDAndLanguageCodeParams) ([]InstitutionAchievement, error)
	GetInstitutionByID(ctx context.Context, id int64) (Institution, error)
	GetInstitutionConferenceByID(ctx context.Context, id int64) (InstitutionConference, error)
	GetInstitutionConferencesByInstitutionIDAndLanguageCode(ctx context.Context, arg GetInstitutionConferencesByInstitutionIDAndLanguageCodeParams) ([]InstitutionConference, error)
	GetInstitutionDetailsByID(ctx context.Context, id int64) (InstitutionDetail, error)
	GetInstitutionDetailsByInstitutionIDAndLanguage(ctx context.Context, arg GetInstitutionDetailsByInstitutionIDAndLanguageParams) (InstitutionDetail, error)
	GetInstitutionLicenceByID(ctx context.Context, id int64) (InstitutionLicence, error)
	GetInstitutionLicencesByInstitutionIDAndLanguageCode(ctx context.Context, arg GetInstitutionLicencesByInstitutionIDAndLanguageCodeParams) ([]InstitutionLicence, error)
	GetInstitutionMagazineByID(ctx context.Context, id int64) (InstitutionMagazine, error)
	GetInstitutionMagazinesByInstitutionIDAndLanguageCode(ctx context.Context, arg GetInstitutionMagazinesByInstitutionIDAndLanguageCodeParams) ([]InstitutionMagazine, error)
	GetInstitutionMainResearchDirectionByID(ctx context.Context, id int64) (InstitutionMainResearchDirection, error)
	GetInstitutionMainResearchDirectionsByInstitutionIDAndLanguage(ctx context.Context, arg GetInstitutionMainResearchDirectionsByInstitutionIDAndLanguageParams) ([]InstitutionMainResearchDirection, error)
	GetInstitutionNamesByLanguageCode(ctx context.Context, languageCode string) ([]string, error)
	GetInstitutionPartnershipByID(ctx context.Context, id int64) (InstitutionPartnership, error)
	GetInstitutionPartnershipsByInstitutionIDAndLanguageCode(ctx context.Context, arg GetInstitutionPartnershipsByInstitutionIDAndLanguageCodeParams) ([]InstitutionPartnership, error)
	GetInstitutionPatentByID(ctx context.Context, id int64) (InstitutionPatent, error)
	GetInstitutionPatentsByInstitutionIDAndLanguageCode(ctx context.Context, arg GetInstitutionPatentsByInstitutionIDAndLanguageCodeParams) ([]InstitutionPatent, error)
	GetInstitutionProjectByID(ctx context.Context, id int64) (InstitutionProject, error)
	GetInstitutionProjectPartnerByID(ctx context.Context, id int64) (InstitutionProjectPartner, error)
	GetInstitutionProjectPartnersByInstitutionProjectIDAndLanguageCode(ctx context.Context, arg GetInstitutionProjectPartnersByInstitutionProjectIDAndLanguageCodeParams) ([]InstitutionProjectPartner, error)
	GetInstitutionProjectsByInstitutionIDAndLanguageCode(ctx context.Context, arg GetInstitutionProjectsByInstitutionIDAndLanguageCodeParams) ([]InstitutionProject, error)
	GetInstitutionRankingByID(ctx context.Context, id int64) (InstitutionRanking, error)
	GetInstitutionRankingsByInstitutionIDAndLanguageCode(ctx context.Context, arg GetInstitutionRankingsByInstitutionIDAndLanguageCodeParams) ([]InstitutionRanking, error)
	GetInstitutionResearchSupportInfrastructureByID(ctx context.Context, id int64) (InstitutionResearchSupportInfrastructure, error)
	GetInstitutionResearchSupportInfrastructuresByInstitutionIDAndLanguageCode(ctx context.Context, arg GetInstitutionResearchSupportInfrastructuresByInstitutionIDAndLanguageCodeParams) ([]InstitutionResearchSupportInfrastructure, error)
	GetInstitutionSocialByID(ctx context.Context, id int64) (InstitutionSocial, error)
	GetInstitutionSocialsByInstitutionID(ctx context.Context, institutionID int64) ([]InstitutionSocial, error)
	GetPersonnelPaginated(ctx context.Context, arg GetPersonnelPaginatedParams) ([]GetPersonnelPaginatedRow, error)
	GetSummaryData(ctx context.Context, languageCode string) ([]GetSummaryDataRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserSessionByToken(ctx context.Context, refreshToken string) (UserSession, error)
	ListUniqueWorkplaces(ctx context.Context, languageCode string) ([]*string, error)
	UpdateEmployeeDegree(ctx context.Context, arg UpdateEmployeeDegreeParams) (EmployeeDegree, error)
	UpdateEmployeeDetails(ctx context.Context, arg UpdateEmployeeDetailsParams) (UpdateEmployeeDetailsRow, error)
	UpdateEmployeeMainResearchArea(ctx context.Context, arg UpdateEmployeeMainResearchAreaParams) (EmployeeMainResearchArea, error)
	UpdateEmployeeMainResearchAreaKeyTopic(ctx context.Context, arg UpdateEmployeeMainResearchAreaKeyTopicParams) (EmployeeMainResearchAreaKeyTopic, error)
	UpdateEmployeeParticipationInEvent(ctx context.Context, arg UpdateEmployeeParticipationInEventParams) (EmployeeParticipationInEvent, error)
	UpdateEmployeeParticipationInProfessionalCommunity(ctx context.Context, arg UpdateEmployeeParticipationInProfessionalCommunityParams) (EmployeeParticipationInProfessionalCommunity, error)
	UpdateEmployeePatent(ctx context.Context, arg UpdateEmployeePatentParams) (EmployeePatent, error)
	UpdateEmployeePublication(ctx context.Context, arg UpdateEmployeePublicationParams) (EmployeePublication, error)
	UpdateEmployeeRefresherCourse(ctx context.Context, arg UpdateEmployeeRefresherCourseParams) (EmployeeRefresherCourse, error)
	UpdateEmployeeResearchActivity(ctx context.Context, arg UpdateEmployeeResearchActivityParams) (EmployeeResearchActivity, error)
	UpdateEmployeeScientificAward(ctx context.Context, arg UpdateEmployeeScientificAwardParams) (EmployeeScientificAward, error)
	UpdateEmployeeSocial(ctx context.Context, arg UpdateEmployeeSocialParams) (EmployeeSocial, error)
	UpdateEmployeeWorkExperience(ctx context.Context, arg UpdateEmployeeWorkExperienceParams) (EmployeeWorkExperience, error)
	UpdateInsitutionDetails(ctx context.Context, arg UpdateInsitutionDetailsParams) (UpdateInsitutionDetailsRow, error)
	UpdateInstitution(ctx context.Context, arg UpdateInstitutionParams) (UpdateInstitutionRow, error)
	UpdateInstitutionAccreditation(ctx context.Context, arg UpdateInstitutionAccreditationParams) (UpdateInstitutionAccreditationRow, error)
	UpdateInstitutionAchievement(ctx context.Context, arg UpdateInstitutionAchievementParams) (UpdateInstitutionAchievementRow, error)
	UpdateInstitutionConference(ctx context.Context, arg UpdateInstitutionConferenceParams) (UpdateInstitutionConferenceRow, error)
	UpdateInstitutionLicence(ctx context.Context, arg UpdateInstitutionLicenceParams) (UpdateInstitutionLicenceRow, error)
	UpdateInstitutionMagazine(ctx context.Context, arg UpdateInstitutionMagazineParams) (UpdateInstitutionMagazineRow, error)
	UpdateInstitutionMainResearchDirection(ctx context.Context, arg UpdateInstitutionMainResearchDirectionParams) (UpdateInstitutionMainResearchDirectionRow, error)
	UpdateInstitutionPartnership(ctx context.Context, arg UpdateInstitutionPartnershipParams) (UpdateInstitutionPartnershipRow, error)
	UpdateInstitutionPatent(ctx context.Context, arg UpdateInstitutionPatentParams) (UpdateInstitutionPatentRow, error)
	UpdateInstitutionProject(ctx context.Context, arg UpdateInstitutionProjectParams) (UpdateInstitutionProjectRow, error)
	UpdateInstitutionProjectPartner(ctx context.Context, arg UpdateInstitutionProjectPartnerParams) (UpdateInstitutionProjectPartnerRow, error)
	UpdateInstitutionRanking(ctx context.Context, arg UpdateInstitutionRankingParams) (UpdateInstitutionRankingRow, error)
	UpdateInstitutionResearchSupportInfrastructure(ctx context.Context, arg UpdateInstitutionResearchSupportInfrastructureParams) (UpdateInstitutionResearchSupportInfrastructureRow, error)
	UpdateInstitutionSocial(ctx context.Context, arg UpdateInstitutionSocialParams) (UpdateInstitutionSocialRow, error)
	UpdateUserSession(ctx context.Context, arg UpdateUserSessionParams) (UpdateUserSessionRow, error)
}

var _ Querier = (*Queries)(nil)
